CREATE TABLE IF NOT EXISTS public.admin_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), admin_adjunto_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, target_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, can_view_profile boolean NOT NULL DEFAULT true, can_view_contributions boolean NOT NULL DEFAULT false, can_view_loans boolean NOT NULL DEFAULT false, can_view_movements boolean NOT NULL DEFAULT false, can_edit boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(admin_adjunto_id,target_user_id));
CREATE TABLE IF NOT EXISTS public.aval_relationships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), socio_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, no_socio_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), active boolean NOT NULL DEFAULT true, UNIQUE(socio_id,no_socio_id));
ALTER TABLE public.loans ADD COLUMN IF NOT EXISTS guarantor_id uuid REFERENCES auth.users(id);
CREATE INDEX IF NOT EXISTS loans_guarantor_id_idx ON public.loans(guarantor_id);
CREATE INDEX IF NOT EXISTS admin_permissions_adjunto_idx ON public.admin_permissions(admin_adjunto_id);
CREATE INDEX IF NOT EXISTS admin_permissions_target_idx ON public.admin_permissions(target_user_id);
CREATE INDEX IF NOT EXISTS aval_relationships_socio_idx ON public.aval_relationships(socio_id);
CREATE INDEX IF NOT EXISTS aval_relationships_no_socio_idx ON public.aval_relationships(no_socio_id);
ALTER TABLE public.admin_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aval_relationships ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles ur WHERE ur.user_id=_user_id AND (ur.role=_role OR (_role='admin'::public.app_role AND ur.role='administrador_principal'::public.app_role))) $$;
CREATE OR REPLACE FUNCTION public.current_app_role() RETURNS public.app_role LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT CASE WHEN EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=auth.uid() AND role='administrador_principal') THEN 'administrador_principal'::public.app_role WHEN EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=auth.uid() AND role='administrador_adjunto') THEN 'administrador_adjunto'::public.app_role WHEN EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=auth.uid() AND role='socio') THEN 'socio'::public.app_role ELSE 'no_socio'::public.app_role END $$;

UPDATE public.user_roles SET role='administrador_principal'::public.app_role WHERE role='admin'::public.app_role;

CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE _is_first boolean; BEGIN SELECT NOT EXISTS(SELECT 1 FROM public.profiles) INTO _is_first; INSERT INTO public.profiles(id,full_name,phone,status) VALUES(NEW.id,COALESCE(NEW.raw_user_meta_data->>'full_name',split_part(COALESCE(NEW.email,''),'@',1)),NEW.raw_user_meta_data->>'phone',CASE WHEN _is_first THEN 'activo'::public.profile_status ELSE 'pendiente'::public.profile_status END) ON CONFLICT(id) DO NOTHING; IF _is_first THEN INSERT INTO public.user_roles(user_id,role) VALUES(NEW.id,'administrador_principal'::public.app_role) ON CONFLICT DO NOTHING; ELSE INSERT INTO public.user_roles(user_id,role) VALUES(NEW.id,'no_socio'::public.app_role) ON CONFLICT DO NOTHING; END IF; RETURN NEW; END; $$;

DROP POLICY IF EXISTS "socios ven su perfil" ON public.profiles; DROP POLICY IF EXISTS "socios actualizan su perfil" ON public.profiles; DROP POLICY IF EXISTS "admin inserta perfiles" ON public.profiles; DROP POLICY IF EXISTS "admin elimina perfiles" ON public.profiles; DROP POLICY IF EXISTS "usuarios ven sus roles" ON public.user_roles; DROP POLICY IF EXISTS "ver aportes propios o admin" ON public.monthly_contributions; DROP POLICY IF EXISTS "socio reporta aporte propio" ON public.monthly_contributions; DROP POLICY IF EXISTS "admin actualiza aportes" ON public.monthly_contributions; DROP POLICY IF EXISTS "admin elimina aportes" ON public.monthly_contributions; DROP POLICY IF EXISTS "ver prestamos propios o admin" ON public.loans; DROP POLICY IF EXISTS "socio solicita prestamo" ON public.loans; DROP POLICY IF EXISTS "admin actualiza prestamos" ON public.loans; DROP POLICY IF EXISTS "admin elimina prestamos" ON public.loans; DROP POLICY IF EXISTS "ver pagos propios o admin" ON public.loan_payments; DROP POLICY IF EXISTS "socio reporta pago propio" ON public.loan_payments; DROP POLICY IF EXISTS "admin actualiza pagos" ON public.loan_payments; DROP POLICY IF EXISTS "admin elimina pagos" ON public.loan_payments;

CREATE POLICY profiles_select ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid() OR public.current_app_role()='administrador_principal' OR (public.current_app_role()='administrador_adjunto' AND EXISTS(SELECT 1 FROM public.admin_permissions p WHERE p.admin_adjunto_id=auth.uid() AND p.target_user_id=profiles.id AND p.can_view_profile)));
CREATE POLICY profiles_update ON public.profiles FOR UPDATE TO authenticated USING(id=auth.uid() OR public.current_app_role()='administrador_principal') WITH CHECK(id=auth.uid() OR public.current_app_role()='administrador_principal');
CREATE POLICY profiles_insert_principal ON public.profiles FOR INSERT TO authenticated WITH CHECK(public.current_app_role()='administrador_principal');
CREATE POLICY profiles_delete_principal ON public.profiles FOR DELETE TO authenticated USING(public.current_app_role()='administrador_principal');
CREATE POLICY roles_select ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.current_app_role()='administrador_principal');
CREATE POLICY permissions_principal ON public.admin_permissions FOR ALL TO authenticated USING(public.current_app_role()='administrador_principal') WITH CHECK(public.current_app_role()='administrador_principal');
CREATE POLICY permissions_adjunto_read ON public.admin_permissions FOR SELECT TO authenticated USING(admin_adjunto_id=auth.uid());
CREATE POLICY aval_principal ON public.aval_relationships FOR ALL TO authenticated USING(public.current_app_role()='administrador_principal') WITH CHECK(public.current_app_role()='administrador_principal');
CREATE POLICY aval_socio_read ON public.aval_relationships FOR SELECT TO authenticated USING(socio_id=auth.uid() OR no_socio_id=auth.uid());
CREATE POLICY contributions_select ON public.monthly_contributions FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.current_app_role()='administrador_principal' OR (public.current_app_role()='administrador_adjunto' AND EXISTS(SELECT 1 FROM public.admin_permissions p WHERE p.admin_adjunto_id=auth.uid() AND p.target_user_id=monthly_contributions.user_id AND p.can_view_contributions)));
CREATE POLICY contributions_insert ON public.monthly_contributions FOR INSERT TO authenticated WITH CHECK(user_id=auth.uid() OR public.current_app_role()='administrador_principal');
CREATE POLICY contributions_update ON public.monthly_contributions FOR UPDATE TO authenticated USING(public.current_app_role()='administrador_principal' OR (user_id=auth.uid() AND status='pendiente')) WITH CHECK(public.current_app_role()='administrador_principal' OR user_id=auth.uid());
CREATE POLICY contributions_delete ON public.monthly_contributions FOR DELETE TO authenticated USING(public.current_app_role()='administrador_principal');
CREATE POLICY loans_select ON public.loans FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.current_app_role()='administrador_principal' OR (public.current_app_role()='administrador_adjunto' AND EXISTS(SELECT 1 FROM public.admin_permissions p WHERE p.admin_adjunto_id=auth.uid() AND p.target_user_id=loans.user_id AND p.can_view_loans)) OR (public.current_app_role()='socio' AND guarantor_id=auth.uid()));
CREATE POLICY loans_insert ON public.loans FOR INSERT TO authenticated WITH CHECK(user_id=auth.uid() OR public.current_app_role()='administrador_principal');
CREATE POLICY loans_update ON public.loans FOR UPDATE TO authenticated USING(public.current_app_role()='administrador_principal') WITH CHECK(public.current_app_role()='administrador_principal');
CREATE POLICY loans_delete ON public.loans FOR DELETE TO authenticated USING(public.current_app_role()='administrador_principal');
CREATE POLICY payments_select ON public.loan_payments FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.current_app_role()='administrador_principal' OR (public.current_app_role()='administrador_adjunto' AND EXISTS(SELECT 1 FROM public.admin_permissions p JOIN public.loans l ON l.id=loan_payments.loan_id WHERE p.admin_adjunto_id=auth.uid() AND p.target_user_id=l.user_id AND p.can_view_loans)) OR (public.current_app_role()='socio' AND EXISTS(SELECT 1 FROM public.loans l WHERE l.id=loan_payments.loan_id AND l.guarantor_id=auth.uid()));
CREATE POLICY payments_insert ON public.loan_payments FOR INSERT TO authenticated WITH CHECK(user_id=auth.uid() OR public.current_app_role()='administrador_principal');
CREATE POLICY payments_update ON public.loan_payments FOR UPDATE TO authenticated USING(public.current_app_role()='administrador_principal') WITH CHECK(public.current_app_role()='administrador_principal');
CREATE POLICY payments_delete ON public.loan_payments FOR DELETE TO authenticated USING(public.current_app_role()='administrador_principal');
REVOKE ALL ON public.admin_permissions,public.aval_relationships FROM anon;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.admin_permissions,public.aval_relationships TO authenticated;
